# -*- Makefile -*-

INSTALL_MODE := unix
include Mkbase.0
LDFLAGS :=
LDLIBS  := -ldl
AR      := gar
STRIP   := gstrip -s
include Mkbase.1

.PHONY: all install

all: libHX.so.${SO_VER} libHX.a

libHX.so.${SO_VER}: ${OBJS}
	${VECHO_LD}
	${Q}${LD} ${LDFLAGS} ${SOFLAGS} -Wl,-h,$@ -o $@ $^ ${LDLIBS};
	ln -fs $@ libHX.so;

libHX.a: ${OBJS}
	${VECHO_AR}
	${Q}${AR} crs $@ $^;

include Mkbase.2
