# -*- Makefile -*-

include Mkbase.0
include Mkbase.1

.PHONY: all

all: libHX.${SO_VER}.dll libHX.a

libHX.${SO_VER}.dll: ${OBJS}
	${VECHO_LD}
	${Q}${LD} ${LDFLAGS} ${SOFLAGS} -Wl,-soname,$@ -o $@ $^ ${LDLIBS};

libHX.a: ${OBJS}
	${VECHO_AR}
	${Q}${AR} crs $@ $^;

include Mkbase.2
