# -*- Makefile -*-

INSTALL_MODE := unix
include Mkbase.0
include Mkbase.1

.PHONY: all install

all: libHX.so.${SO_VER}

libHX.so.${SO_VER}: ${OBJS}
	${VECHO_LD}
	${Q}${LD} ${LDFLAGS} ${SOFLAGS} -Wl,-soname,$@ -o $@ $^;

include Mkbase.2
