#!/bin/bash

case "`uname`" in
    (Linux)
	exec make -f Makefile.linux "$@";
	;;
    (FreeBSD|OpenBSD|NetBSD)
	exec gmake -f Makefile.bsd "$@";
	;;
    (MINGW*|mingw*)
	exec make -f Makefile.mingw "$@";
	;;
    (CYGWIN*|cygwin*)
	exec make -f Makefile.cygwin "$@";
	;;
    (SunOS)
	exec gmake -f Makefile.sunos "$@";
	;;
    *)
	echo "No clue how to build for system"
	;;
esac;

exit 1;
