#!/bin/sh -ex

if [ -z "$srcdir" ]; then
	srcdir=".";
fi;
rm -f libHX_Documentation.pdf
lyx -e pdf2 "$srcdir/libHX_Documentation.lyx" || :
# lyx-2.3.2 does not work with texlive-babel-2017.135.3
# """
# Package babel Error: You haven't specified a language option.
# ...ry to proceed from here, type x to quit.)
#
# You need to specify a language, either as a global option
# or as an optional argument to the \usepackage command;
# You shouldn't try to proceed form here, type x to quit.
# """
# babel you so stupid for breaking backward comapt.

test -e libHX_Documentation.pdf
